Document: bruce
Title: Debian bruce Manual
Author: <insert document author here>
Abstract: This manual describes what bruce is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bruce/bruce.sgml.gz

Format: postscript
Files: /usr/share/doc/bruce/bruce.ps.gz

Format: text
Files: /usr/share/doc/bruce/bruce.text.gz

Format: HTML
Index: /usr/share/doc/bruce/html/index.html
Files: /usr/share/doc/bruce/html/*.html
